export const environment = {
  production: false,
  //apiUrl:'http://localhost:3000/api/v1',
  apiUrl: 'https://wineinventory-back-end.azurewebsites.net/api/v1',
  warehousesEndpointPath: '/warehouses',
  productsEndpointPath: '/products',
  reportsEndpointPath: '/reports',
  zonesEndpointPath: '/zones',
  userEndpointPath: '/users',
  profileEndpointPath: '/profiles',
  accountsEndpointPath: '/accounts',
  catalogEndpointPath: '/catalog',
  //baseServerUrl: 'http://localhost:8080/api/v1',
  baseServerUrl: 'https://wineinventory-back-end.azurewebsites.net/api/v1',
  authEndpointPath: '/authentications',
  accountWarehousesEndpointPath: '/accounts/{accountId}/warehouses',
  accountProductsEndpointPath: '/accounts/{accountId}/products',
  reportingEndpointPath: '/reporting',
  inventoriesEndpointPath: '/inventories',
  careguidesEndpointPath: '/careguides',
  plansEndpointPath: '/plans',
  subscriptionUpdateEndpointPath:'/accounts/{accountId}/subscriptions/{subscriptionId}',
  subscriptionEndpointPath: '/accounts/{accountId}/subscriptions',
  subscriptionPaypalEndpointPath:'/accounts/{accountId}/subscriptions'
};

